### PR TITLE
Allow to pass UDP options when starting the Client UDP socket

### PR DESCRIPTION
**Pull request by eduardo-cunha-bose**
This is useful if for instance we want to have bigger send and receive buffers.

### CODE REVIEW

**Comment by entone** [comment]
Test fails on my local machine

Linux PopOS 20.04

Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.1)

```elixir
▶ mix test

11:19:05.507 [debug] Testing Server

11:19:05.509 [debug] {192, 168, 0, 187}

11:19:05.509 [debug] Address: {192, 168, 0, 187}

11:19:05.509 [debug] Hostname: _jE8g0eyDM.local

11:19:05.756 [debug] {:ok, {:hostent, '_jE8g0eyDM.local', [], :inet, 4, [{192, 168, 0, 187}]}}

11:19:05.756 [debug] Testing Client


  1) test client and server (MdnsTest)
     test/mdns_test.exs:35
     match (=) failed
     code:  assert {:ok, [recbuf: 12345]} = :inet.getopts(udp_socket, [:recbuf])
     right: {:ok, [recbuf: 24690]}
     stacktrace:
       test/mdns_test.exs:58: (test)



Finished in 0.3 seconds
1 test, 1 failure

Randomized with seed 425859
```

**Comment by eduardo-cunha-bose** [comment]
Probably `12345` is below the minimum size of the UDP receive buffer on your OS..
What do you think about using the value `123456`? It should be inside the min and max values of the buffer size in all OS's (I hope).

**Comment by entone** [comment]
It looks like the `recbuf` is doubled up to a certain max size

```elixir
     code:  assert {:ok, [recbuf: 8193]} = :inet.getopts(udp_socket, [:recbuf])
     right: {:ok, [recbuf: 16386]}

     code:  assert {:ok, [recbuf: 5000]} = :inet.getopts(udp_socket, [:recbuf])
     right: {:ok, [recbuf: 10000]}

     code:  assert {:ok, [recbuf: 123456]} = :inet.getopts(udp_socket, [:recbuf])
     right: {:ok, [recbuf: 246912]}

     code:  assert {:ok, [recbuf: 500000]} = :inet.getopts(udp_socket, [:recbuf])
     right: {:ok, [recbuf: 425984]}
```

**Comment by eduardo-cunha-bose** [comment]
That behaviour is quite strange..
I'm on macOS and it sets the provided value.

**Comment by eduardo-cunha-bose** [comment]
I can change the test use a different option 🤷‍♂️

**Comment by entone** [comment]
> That behaviour is quite strange..
> I'm on macOS and it sets the provided value.

Super weird. That works for me. Something that should be consistent across OS

**Comment by eduardo-cunha-bose** [comment]
Changed it to use the `buffer` option

**Comment by entone** [comment]
Published 1.0.7

**Pull request merged**
