### PR TITLE
Fix Client parsing of DNS Resource of type TXT

### LINKED ISSUE #9: Question - How to serve a record with a payload?
I've been playing with Mdns.Server and Mdns.Client for a little while, but I can't figure out how to serve a record with a payload. I want to do something like the googlecast example in the Readme:
Is that possible with this mdns Elixir library?

```elixir
{:"_googlecast._tcp.local",
    %Mdns.Client.Device{
        domain: "CRT-Labs.local",
        ip: {192, 168, 1, 138},
        payload: %{
            "bs" => "FA8FCA79C426",
            "ca" => "4101",
            "fn" => "CRT-Labs",
            "ic" => "/setup/icon.png",
            "id" => "e0617de7e2df63476fab257c8327ef3b",
            "md" => "Chromecast",
            "rm" => "E81C9A486980AA48",
            "rs" => "",
            "st" => "0",
            "ve" => "05"
        },
        services: [
            "CRT-Labs._googlecast._tcp.local"
        ]
    }
}
```

### PR DESCRIPTION
**Pull request by eduardo-cunha-bose**
This should fix #9

### CODE REVIEW

**Comment by entone** [comment]
@eduardo-cunha-bose awesome!

I know the tests aren't much right now, but would you mind adding one for this?

**Comment by eduardo-cunha-bose** [comment]
I'm getting the following error with the current test:

```
# mix test

16:13:28.528 [debug] Testing Server

16:13:28.546 [debug] {172, 17, 0, 2}

16:13:28.554 [debug] Address: {172, 17, 0, 2}

16:13:28.554 [debug] Hostname: TW49GQ-cOH.local

16:13:33.577 [debug] {:error, :nxdomain}


  1) test client and server (MdnsTest)
     test/mdns_test.exs:35
     match (=) failed
     code:  assert {:ok, {:hostent, char_host, [], :inet, 4, [address]}} = lookup
     left:  {:ok, {:hostent, char_host, [], :inet, 4, [address]}}
     right: {:error, :nxdomain}
     stacktrace:
       test/mdns_test.exs:53: (test)
```

**Comment by entone** [comment]
Are you running MacOS?

**Comment by entone** [comment]
If you are, I believe you have to disable mDNSResonder in order to run the tests.

**Comment by eduardo-cunha-bose** [comment]
I was running inside an alpine docker container

**Comment by eduardo-cunha-bose** [comment]
Anyway, disabling the mDNSResonder I was able to run the tests locally and it worked okay.
Thanks for the tip.

**Comment by entone** [comment]
Thank you! Looks good.

**Comment by entone** [comment]
New version published to hex.pm, https://hex.pm/packages/mdns/1.0.4

Thanks again!

**Pull request merged**
