### PR TITLE
Add support for NSEC

### PR DESCRIPTION
**Pull request by mickel8**
related with #18

### CODE REVIEW

**Comment by mickel8** [comment]
What I am not sure about is that when sending 2 mDNS requests one that resolves to IPv4 and the second one that resolves to IPv6 I am getting about 8-12 resposnes :thinking:

**Comment by mickel8** [comment]
This works I mean with these changes now I can successfully connect to my browser which sends mDNS ICE candidates but the number of notifications scares me a little as in Wireshark I can see only two requests and two responses.

**Comment by entone** [comment]
It really depends on the device, in this case your browser. Some will send
multiple responses. As it's all UDP, there are no delivery guarantees, so
some will send multiple responses. In addition, many devices broadcast the
information at a regular interval without a query.

I don't think it has anything to do with the code.

**Comment by entone** [comment]
Would it be possible to update the tests for these new response types?

**Comment by mickel8** [comment]
> Would it be possible to update the tests for these new response types?

Sure. I will try to do this today or on Monday morning.

**Comment by mickel8** [comment]
@entone I have updated tests for NSEC records. I have also removed support for IPv6 records (I am not sure how to do it properly)

**Comment by entone** [comment]
Thank you! Published to Hex, https://hex.pm/packages/mdns

**Comment by mickel8** [comment]
Thank you!

**Pull request merged**
